export const entries = [
    {
        id: '0',
        title: 'to you humans...(and you virtual traffic r0b0c0ps...)',
        writeDate: '02feb2024',
        publishDate: '00jan0000',
        interaction: 1,
        content: "HEY, everyone. I'm Kendall, and I started this blog to dump my thoughts onto the interwebs and to add something to my software/web dev portfolio. This is daunting, as I've never been a very public person, but I've definitely experienced the power of communication over the past few years--sometimes thrusted into the fray, other times making my voice heard on my own volition. These experiences yielded net-positive and net-negative consequences, and it is because of these consequences that I'm writing this blog post in this moment. As a human being using discernment with <a href='https://qz.com/866352/scientists-say-your-mind-isnt-confined-to-your-brain-or-even-your-body#:~:text=In%20other%20words,to%20predict%20result)'>a human mind emergent of a human brain</a>: <br/><br/><ol><li>1) I am convinced that the positive and the negative make this whole thing worthwhile.</li><li>2) I am convinced that sharing some of the lessons I've learned and trains of thought I've picked up along the way makes this worthwhile. </li></ol><br/>That may be a cool research topic: <i>What amount of information/evidence is sufficient in determining personal conviction? What happens in the brain when one truly considers themself convinced?</i> Anyway, I am also motivated by my journaling and the conversations I've had with others concerning some of the thoughts I've copied and pasted from mind to paper. I'll probably be posting a few times a week. I don't really have a schedule yet. The most recent post will be at the top of my feed, but all posts will have tags you can search for. I'll also place each post into a category. As of right now, I'm thinking 'General' and 'Music'. You can select categories on the 'Posts' page. Check out my bio to learn more about me, and feel free to follow me on socials (links on bio page). Thanks for joining me as I toggle the visibility of my many wandering thoughts from private to public.",
    }
]